name: Check & fix styling

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   name: Run PHP CS Fixer
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --config=.php-cs-fixer.dist.php --allow-risky=yes

            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Fix styling
